swagger: '2.0'
info:
  version: 1.0.3
  title: Airport On-Time Performance
  x-tags:
    - '#ama-for-dev'
  x-status: validated
  x-release-note:
    '1.0':
      - Initial Version
  description: "Before using this API, we recommend you read our\_**[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)**\_for more information on how to generate an access token."
host: test.api.amadeus.com
basePath: /v1
schemes:
  - https
consumes:
  - application/vnd.amadeus+json
produces:
  - application/vnd.amadeus+json
paths:
  /airport/predictions/on-time:
    get:
      tags:
        - airport-ontime-prediction
      operationId: getAirportOnTimePrediction
      summary: Returns a percentage of on-time flight departures from a given airport.
      parameters:
        - name: airportCode
          in: query
          description: 'airport [IATA code](http://www.iata.org/publications/Pages/code-search.aspx), e.g. BOS for Boston'
          required: true
          type: string
          pattern: '[A-Z]{3}'
          x-example: JFK
        - name: date
          in: query
          description: 'the date on which the traveler will depart from the give airport. Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2019-12-25'
          required: true
          type: string
          format: date
          x-example: '2020-12-01'
      responses:
        '200':
          $ref: '#/responses/200'
        '400':
          $ref: '#/responses/400'
        default:
          $ref: '#/responses/500'
      description: ''
definitions:
  Prediction:
    type: object
    properties:
      data:
        $ref: '#/definitions/OnTimePrediction'
      meta:
        $ref: '#/definitions/Meta'
    example:
      data:
        id: JFK20201201
        probability: '0.928'
        result: '0.85957181'
        subType: on-time
        type: prediction
      meta:
        links:
          self: 'https://test.api.amadeus.com/v1/airport/predictions/on-time?airportCode=JFK&date=2020-12-01'
  Meta:
    type: object
    properties:
      links:
        $ref: '#/definitions/Links'
  OnTimePrediction:
    properties:
      type:
        description: the resource name (`prediction`)
        type: string
      subType:
        type: string
        example: trip-purpose
      id:
        description: item identifier
        type: string
        readOnly: true
      result:
        $ref: '#/definitions/PredictionResultType'
      probability:
        description: probability of the forecast (between 0 and 1)
        type: string
  PredictionResultType:
    description: forecast description
    type: string
    example: 0.8
  Links:
    properties:
      self:
        type: string
        format: uri
      related:
        type: string
        format: uri
      type:
        type: string
  Error_400:
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Issue'
    required:
      - errors
    example:
      errors:
        - status: 400
          code: 477
          title: INVALID FORMAT
          detail: invalid query parameter format
          source:
            parameter: airport
            example: CDG
  Error_500:
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Issue'
    required:
      - errors
    example:
      errors:
        - status: 500
          code: 141
          title: SYSTEM ERROR HAS OCCURRED
  Issue:
    properties:
      status:
        description: the HTTP status code applicable to this error
        type: integer
      code:
        description: an application-specific error code
        type: integer
        format: int64
      title:
        description: a short summary of the error
        type: string
      detail:
        description: explanation of the error
        type: string
      source:
        type: object
        title: Issue_Source
        description: an object containing references to the source of the error
        maxProperties: 1
        properties:
          pointer:
            description: 'a JSON Pointer [RFC6901] to the associated entity in the request document'
            type: string
          parameter:
            description: a string indicating which URI query parameter caused the issue
            type: string
          example:
            description: a string indicating an example of the right value
            type: string
responses:
  '200':
    description: Success
    schema:
      $ref: '#/definitions/Prediction'
  '400':
    description: "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n4926    | INVALID DATA RECEIVED               \n32171   | MANDATORY DATA MISSING \t     \n"
    schema:
      $ref: '#/definitions/Error_400'
  '500':
    description: Unexpected Error
    schema:
      $ref: '#/definitions/Error_500'
x-generatedAt: '2020-07-23T14:07:22.902Z'
