swagger: '2.0'
info:
  version: 1.1.1
  title: Flight Most Booked Destinations
  x-tags:
    - '#ama-for-dev'
  x-status: validated
  x-release-note:
    1.1.0:
      - AFD-1091 - change from "traveller" to "traveler"
      - Correct example
      - Naming of parameter origin changed for originCityCode
    '1.0':
      - Initial Version
  description: "\nBefore using this API, we recommend you read our\_**[Authorization Guide](https://developers.amadeus.com/self-service/apis-docs/guides/authorization-262)**\_for more information on how to generate an access token.\n\nPlease also be aware that our test environment is based on a subset of the production, this API in test only returns a few selected cities. You can find the list in our **[data collection](https://github.com/amadeus4dev/data-collection)**."
host: test.api.amadeus.com
basePath: /v1
schemes:
  - https
consumes:
  - application/vnd.amadeus+json
produces:
  - application/vnd.amadeus+json
paths:
  /travel/analytics/air-traffic/booked:
    get:
      tags:
        - air-traffic
      operationId: getAirTraffic
      summary: Returns a list of air traffic reports.
      parameters:
        - name: originCityCode
          description: 'Code for the origin city following IATA standard ([IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx)). - e.g. BOS for Boston'
          in: query
          required: true
          type: string
          pattern: '[A-Za-z]{3}'
          x-example: MAD
        - name: period
          description: |
            period when consumers are traveling.
            * It can be a month only. 
            * ISO format must be used - e.g. 2015-05. 
            * Period ranges are not supported. 
            * Only periods from 2011-01 up to previous month are valid. 
            * Future dates are not supported.
          in: query
          required: true
          type: string
          x-example: 2017-08
        - name: max
          description: maximum number of destinations in the response. Default value is 10 and maximum value is 50.
          in: query
          required: false
          default: 10
          type: number
          format: integer
        - $ref: '#/parameters/fields'
        - $ref: '#/parameters/pageLimit'
        - $ref: '#/parameters/pageOffset'
        - $ref: '#/parameters/sort'
      responses:
        '200':
          $ref: '#/responses/air-traffic'
        '400':
          $ref: '#/responses/400'
        default:
          $ref: '#/responses/500'
      description: ''
parameters:
  pageLimit:
    name: 'page[limit]'
    description: maximum items in one page
    required: false
    in: query
    type: integer
    default: 10
  pageOffset:
    name: 'page[offset]'
    description: start index of the requested page
    required: false
    in: query
    type: integer
    default: 0
  sort:
    description: |
      defines on which attribute the sorting will be done:
      * analytics.flights.score - sort destinations by flights score (decreasing)
      * analytics.travelers.score - sort destination by traveler's score (decreasing)
    name: sort
    required: false
    in: query
    type: string
    default: analytics.travelers.score
    enum:
      - analytics.flights.score
      - analytics.travelers.score
  fields:
    name: fields
    required: false
    in: query
    type: string
    description: |-
      list of attributes desired in the response or list of attributes to remove from the response (with "-" before fields) 
      * The attributes names must contain the whole path (except resource name) e.g. travelers
definitions:
  Air_Traffic:
    properties:
      type:
        type: string
        example: air-traffic
      subType:
        type: string
      destination:
        description: 'IATA code of the destination city - [IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx)'
        type: string
        example: WAS
      analytics:
        $ref: '#/definitions/Analytics'
  Error_400:
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Issue'
    required:
      - errors
    example:
      errors:
        - status: 400
          code: 477
          title: INVALID FORMAT
          detail: invalid query parameter format
          source:
            parameter: airport
            example: CDG
  Error_500:
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/Issue'
    required:
      - errors
    example:
      errors:
        - status: 500
          code: 141
          title: SYSTEM ERROR HAS OCCURRED
  Issue:
    properties:
      status:
        description: the HTTP status code applicable to this error
        type: integer
      code:
        description: an application-specific error code
        type: integer
        format: int64
      title:
        description: a short summary of the error
        type: string
      detail:
        description: explanation of the error
        type: string
      source:
        type: object
        title: Issue_Source
        description: an object containing references to the source of the error
        maxProperties: 1
        properties:
          pointer:
            description: 'a JSON Pointer [RFC6901] to the associated entity in the request document'
            type: string
          parameter:
            description: a string indicating which URI query parameter caused the issue
            type: string
          example:
            description: a string indicating an example of the right value
            type: string
  Collection_Meta:
    title: Collection_Meta
    properties:
      count:
        type: integer
        example: 1
      links:
        title: CollectionLinks
        properties:
          self:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
          next:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
          previous:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
          last:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
          first:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
          up:
            type: string
            format: uri
            example: 'https://test.api.amadeus.com/v1/area/resources?...'
        example:
          self: 'https://test.api.amadeus.com/v1/area/resources?param=value'
  Analytics:
    properties:
      flights:
        $ref: '#/definitions/Flights'
      travelers:
        $ref: '#/definitions/Travelers'
  Flights:
    properties:
      score:
        type: number
        format: integer
        description: Approximate score for ranking purposes calculated based on number of flights from / to the airport or city
        example: 56
  Travelers:
    properties:
      score:
        type: number
        format: integer
        description: Approximate score for ranking purposes calculated based on number of travelers in the location.
        example: 68
responses:
  '400':
    description: "code    | title                                 \n------- | ------------------------------------- \n477     | INVALID FORMAT\n572     | INVALID OPTION\n2781    | INVALID LENGTH\n4926    | INVALID DATA RECEIVED                               \n32171   | MANDATORY DATA MISSING \t     \n"
    schema:
      $ref: '#/definitions/Error_400'
  '500':
    description: Unexpected Error
    schema:
      $ref: '#/definitions/Error_500'
  air-traffic:
    description: Successful Operation
    schema:
      title: Success
      required:
        - data
      properties:
        warnings:
          type: array
          items:
            $ref: '#/definitions/Issue'
        meta:
          $ref: '#/definitions/Collection_Meta'
        data:
          type: array
          items:
            $ref: '#/definitions/Air_Traffic'
      example:
        meta:
          count: 10
          links:
            self: 'https://test.api.amadeus.com/v1/travel/analytics/air-traffic/booked?originCityCode=MAD&page%5Blimit%5D=10&page%5Boffset%5D=0&period=2017-08'
        data:
          - type: air-traffic
            destination: PAR
            subType: BOOKED
            analytics:
              flights:
                score: 100
              travelers:
                score: 100
          - type: air-traffic
            destination: TCI
            subType: BOOKED
            analytics:
              flights:
                score: 61
              travelers:
                score: 80
          - type: air-traffic
            destination: LON
            subType: BOOKED
            analytics:
              flights:
                score: 93
              travelers:
                score: 65
          - type: air-traffic
            destination: BCN
            subType: BOOKED
            analytics:
              flights:
                score: 91
              travelers:
                score: 61
          - type: air-traffic
            destination: NYC
            subType: BOOKED
            analytics:
              flights:
                score: 61
              travelers:
                score: 51
          - type: air-traffic
            destination: BRU
            subType: BOOKED
            analytics:
              flights:
                score: 41
              travelers:
                score: 39
          - type: air-traffic
            destination: UIO
            subType: BOOKED
            analytics:
              flights:
                score: 48
              travelers:
                score: 37
          - type: air-traffic
            destination: SDQ
            subType: BOOKED
            analytics:
              flights:
                score: 15
              travelers:
                score: 19
          - type: air-traffic
            destination: DXB
            subType: BOOKED
            analytics:
              flights:
                score: 22
              travelers:
                score: 11
          - type: air-traffic
            destination: OPO
            subType: BOOKED
            analytics:
              flights:
                score: 18
              travelers:
                score: 8
x-generatedAt: '2020-07-23T09:58:30.654Z'
